version: '3.8'
services:
  crop-classification:
    build: .
    ports:
      - "8000:8000"
    environment:
      - OPIE_API_KEY=09fac56e-fdcf-460a-9f39-05a2bda3f3cf
      - OPIE_API_URL=https://api.opie.com
      - GEMINI_API_KEY=your_gemini_api_key_here
    volumes:
      - ./app:/app
